remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: AutoSort+
description: Fully customizable AI-powered email organization for Thunderbird. Create your own folder structure and let the AI adapt to your organizational system.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

# Navigation
nav:
  - title: Installation
    url: /installation
  - title: Your Custom Setup
    url: /custom-setup
  - title: Usage Guide
    url: /usage
  - title: FAQ
    url: /faq
  - title: Contributing
    url: /contributing 