remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: AutoSort+
description: AI-powered email organization addon for Thunderbird
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

# Navigation
nav:
  - Installation: installation.md
  - Configuration: configuration.md
  - Usage Guide: usage.md
  - FAQ: faq.md
  - Contributing: contributing.md 